<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBlogAdspacesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('blog_adspaces', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255);
            $table->integer('adblock_id');
            $table->integer('order');
            $table->string('position', 255);
            $table->string('route', 255);
            $table->nullableTimestamps();

            $table->unique('position', 'adspaces_position_unique');
            $table->index('adblock_id', 'adspaces_adblock_id_index');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('blog_adspaces');
    }
}
