<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBlogNavsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('blog_navs', function (Blueprint $table) {
            $table->increments('nav_id');
            $table->string('nav_name', 50)->nullable()->comment('//名称');
            $table->string('nav_alias', 50)->nullable()->comment('//别名');
            $table->string('nav_url', 255)->nullable()->comment('//url');
            $table->integer('nav_order')->nullable()->comment('//排序');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('blog_navs');
    }
}
