<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBlogLinksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('blog_links', function (Blueprint $table) {
            $table->increments('link_id');
            $table->string('link_name', 255)->comment('//名称');
            $table->string('link_title', 255)->comment('//标题');
            $table->string('link_url', 255)->comment('//链接');
            $table->integer('link_order')->comment('//排序');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('blog_links');
    }
}
