<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBlogStatsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('blog_stats', function (Blueprint $table) {
            $table->increments('id');
            $table->string('day', 255);
            $table->integer('register_count');
            $table->integer('thread_count');
            $table->integer('reply_count');
            $table->integer('image_count');
            $table->nullableTimestamps();

            $table->index('day', 'stats_day_index');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('blog_stats');
    }
}
