<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBlogAdvertisementsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('blog_advertisements', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255);
            $table->integer('adspace_id');
            $table->text('body');
            $table->nullableTimestamps();

            $table->index('adspace_id', 'advertisements_adspace_id_index');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('blog_advertisements');
    }
}
